[[plugins]]
repo = 'majutsushi/tagbar'

[[plugins]]
repo = 'davidhalter/jedi-vim'
on_ft = 'python'
hook_add = '''
  let g:jedi#force_py_version = 3
  let g:jedi#auto_initialization = 1
  let g:jedi#popup_select_first = 0
  let g:jedi#popup_on_dot = 0
  let g:jedi#show_call_signatures = 1
  let g:jedi#completions_command = "<C-k>"
  autocmd FileType python setlocal completeopt-=preview
'''

[[plugins]]
repo = 'plytophogy/vim-virtualenv'
on_ft = 'python'

[[plugins]]
repo = 'Vimjas/vim-python-pep8-indent'
on_ft = 'python'

[[plugins]]
repo = 'kannokanno/previm'
on_ft = ['markdown','mkd']
hook_add = '''
  let g:previm_open_cmd = 'open -a /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome'
'''

[[plugins]]
repo = 'mattn/emmet-vim'
on_ft = ['html','css']

[[plugins]]
repo = 'zchee/deoplete-jedi'
on_ft = 'python'

[[plugins]]
on_ft = ['c', 'cpp', 'cmake']
repo = 'zchee/deoplete-clang'
hook_source = '''
  " let g:deoplete#sources#clang#libclang_path = '/Library/Developer/CommandLineTools/usr/lib/libclang.dylib'
  " let g:deoplete#sources#clang#clang_header = '/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang'
  let g:deoplete#sources#clang#libclang_path = '/usr/local/Cellar/llvm/7.0.1/lib/libclang.dylib'
  let g:deoplete#sources#clang#clang_header = '/usr/local/Cellar/llvm'
'''

[[plugins]]
repo = 'zchee/deoplete-go'
on_ft = 'go'

[[plugins]]
repo = 'poppyschmo/deoplete-latex'
on_ft = 'tex'
hook_add = '''
  let g:deoplete#sources#latex#include_web_math = 1  " default 0
'''

[[plugins]]
repo = 'cespare/vim-toml'
on_ft = ['toml']

[[plugins]]
repo = 'huawenyu/neogdb.vim'
on_ft = ['c', 'cpp']

[[plugins]]
repo = 'lervag/vimtex'
on_ft = ['tex']
hook_add ='''
  let g:vimtex_compiler_latexmk_engines = { '_' : '-pdfdvi' }
  let g:vimtex_compiler_latexmk = {
    \ 'background': 1,
    \ 'build_dir': '',
    \ 'continuous': 1,
    \ 'options': [
    \    '-pdfdvi', 
    \    '-verbose',
    \    '-file-line-error',
    \    '-synctex=1',
    \    '-interaction=nonstopmode',
    \    '-pdf',
    \],
    \}

  let g:vimtex_view_general_viewer
    \ = '/Applications/Skim.app/Contents/SharedSupport/displayline'
  let g:vimtex_view_general_options = '-r @line @pdf @tex'
  if has('nvim')
    let g:vimtex_compiler_progname
          \ = 'nvr'
  endif
'''
